   
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
sphinx:
  configuration: docs/source/conf.py
python:
  install:
  - method: pip
    path: .
conda:
  environment: environment.yml
