name: Linux Conda

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  build-linux-conda:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '3.10'
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install mamba
      run: |
        mkdir -p $HOME/.conda_pkgs_cache
        conda config --add pkgs_dirs "$HOME/.conda_pkgs_cache"
        conda install -c conda-forge mamba python=3.10
        conda clean -a
        
    - name: install mesmerize-core
      run: |
        mamba env update -n base --file environment.yml
        caimanmanager install
        pip install .
        
    - name: Test with pytest
      run: |
        mamba install pytest
        DOWNLOAD_GROUND_TRUTHS=1 pytest -s .

