# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linux pip

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-linux-pip:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        
    - name: Install deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        
    - name: install caiman
      run: |
        cd ..
        git clone https://github.com/flatironinstitute/CaImAn.git
        cd CaImAn
        pip install .
        caimanmanager install

    - name: Install mesmerize-core
      run: |
        pip install .
        
    - name: Test with pytest
      run: |
        pip install pytest
        DOWNLOAD_GROUND_TRUTHS=1 pytest -s .
