name: MacOS Conda

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  build-macos-conda:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@v2
      with:
        condarc: "channel_priority: flexible"
        environment-name: mescore
        environment-file: environment.yml
        create-args: -c conda-forge -c defaults python=3.10 pytest
        
    - name: Test mesmerize-core with pytest
      shell: bash -el {0}
      run: |
        caimanmanager install
        pip install .
        CONDA_EXE="$MAMBA_EXE" DOWNLOAD_GROUND_TRUTHS=1 pytest -s .

