name: MacOS Conda

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches: [ master ]

jobs:
  build-macos-conda:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.10'
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: mescore
        environment-file: environment.yml
        
    - name: Test mesmerize-core with pytest
      shell: bash -el {0}
      run: |
        conda activate mescore
        mamba install pytest
        caimanmanager install
        pip install .
        DOWNLOAD_GROUND_TRUTHS=1 pytest -s .

